include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for ChinaDNS
LUCI_DEPENDS:=+luci-compat +dns-forwarder
LUCI_PKGARCH:=all
PKG_LICENSE:=GPLv3

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
